version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Europe/Rome
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge-candidate
    commit-message:
      prefix: chore(deps)
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:30'
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: chore(ci)
    groups:
      github-actions:
        patterns:
          - '*'
